name: 'Setup Go'
description: 'Setup Go environment with caching'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.25'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
