name: 'Checkout and Setup Go'
description: 'Checkout code and setup Go environment with caching'

inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.25'
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags'
    required: false
    default: '0' # Shallow clones should be disabled for a better relevancy of analysis

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    
    - uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
        cache: true
